table 'City Metrics'
	lineageTag: 4b92ee6c-8789-4bf0-80e5-621598d99958

	column City
		dataType: string
		lineageTag: 6dce4cd5-3854-484f-a00a-926630f16a84
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 74e0e447-96d6-4154-9129-e80e7a16ba28
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 289c28af-bd3c-43d1-ba17-574c2a21e548
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 491e4ace-5c14-41c7-b0e3-da17829ef92e
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Rank
		dataType: int64
		formatString: 0
		lineageTag: 6495d10d-9a06-420d-a266-160fc5c4aab7
		summarizeBy: sum
		sourceColumn: Rank

		annotation SummarizationSetBy = Automatic

	column AttributeOrder
		dataType: int64
		formatString: 0
		lineageTag: 6b748d15-3695-4476-973a-589dc16a0ab6
		summarizeBy: sum
		sourceColumn: AttributeOrder

		annotation SummarizationSetBy = Automatic

	column ValueForGrouping
		dataType: double
		lineageTag: 02a01ae3-5f7e-4d97-9179-7f28676de736
		summarizeBy: sum
		sourceColumn: ValueForGrouping

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Region
		dataType: string
		lineageTag: 4773d9ee-6661-4d62-a715-5a6919666c7c
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Region Rank'
		dataType: int64
		formatString: 0
		lineageTag: 63142753-0189-4c64-a356-1bf4db2654dd
		summarizeBy: sum
		sourceColumn: Region Rank

		annotation SummarizationSetBy = Automatic

	partition 'City Metrics' = m
		mode: import
		source =
				let
				    // This data was manually populated in Power Query.
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fVlNj+zGDfwrwZ4NQf3F7j4mQRDkYhjwwQfDh3l5k+wim51g3tr++yZZ1VrNqpWTrOctsckmi0XOzz8//eX+crn/73Z/f/ruKa6h2KMuoo8altr0mWRZ7b3Epdh7aUt9+uW7A9T+JvZF7BN1XXo3bNuwawQ29xm42qMtYs+aFqFhey0B/1z6kmSG9b9dl9WxeWluuC416DPXJWR9ymrvE3DHqaOfWpYcAHZvsp7ePi7BTn8Ex9UesgjD1fwkZUkB4Nxw7JZn4IBQZ3hs9lNfur2WupSCaLUZMuLMOSPS/p5Xi45i9J3RijOHY7JHgYOiUeqIND5S/ByK7VN/zWDMSAMpy2rvKduVKlbTJT74+/fb69fr259+fL5dXr99pFdSZzONB3hd7cSS6EG2D598QPABzw/RCAtdp+XoH9AbqGcfqDjy+EDLOHpIvOeKE/TTEzR8oPiRO+5NvyPAJ8C1CE7gHSkiDKFfh0Yg8Lr9+tNS5QTvKWfXNSJmx49LC0ibmhnAM/uedYmp6nlraPvvUaHZ/t8JOOLwnjPqewPcC0yDHxh8SWd4d1btFRj0U+eERN6CdwbO8Bw3FVGZljvwPDByEZ7/ePv1/fm/1/v1I+80TQqr2i9RKwi3LUvxMLYZUpAfyVMc1hRYmKjnuAqc84nWZCawMUHyObIB6cFSZMqgN3DvRi4zpJ8xo5SVNYHUu+b7eor0rMrM/iyoTz2tc7ilYz1Fki9hI8KGFmgmc7eKuLU6A5O43Fwu8DPT77Wc2mTNrIyt315soKHC2pojMwwGBGp1YCXpilXdBvzp5fX19vu/bvevuwyKoDiFNjaswrqHK3OoAJISsl3SLriyPiTfZ2ilNR5YIg7cCO3lHOpBKPSpoOAtSJHl83+sdviKaAkyzqolI77reZiQSPonHc/CJlcTqnQ9D1OkjwWJEztdZQ/t7RwZkQ+eg3rezIoJAeet58iEvA8jWzuQXqUieD+BsnH4bRZymBZbKoCmndUf7peX+8v1y/Vtl0zaQ7qbaQiw8urKJHNyUZaKc7T3QHVzCK2Gkuu8LRIiW+AB7Q2wwDBkVhxEnik+Tk5NddMflENBRtnFER37HE6h0Xns0QycKRLPol6LTOFofA2ZpSpv9GEXblYiCfATt0ffc0lWC1jGlAj7d0AZs+0f0BHGDKQ6z2WKHl2YPpXStqc52m1V2EiIHz6hOq8jaBSnByizSihPmThADcXXh9N/vV+/vf9+eb/ed5xFRlXnXLIoAflxE9POtGaaoikO0ggN3/0rWm1IfDFOmqErbEOQVXatxGsbZS0jWT6jG0/OSugVtjvRaL9i88kMzT7oJ5RM0klMlRUpZCefokcvdNt6XZ4xmU/L0/JwY5/RYUcLGrVMWe2d1Xox9fU6vbHREIWKyhtTpmBSXnIVYvPXNGojzxoLtLCbgzAypjlxXTBDZ9yr35z2luh+U1IOcrKTI2r/uN/evlx2iWalbQdokXPPmAs6xjfL/H6ECknFIG2onsReE6GfTCpOrFZY9VasVgvlK1KvLrz9Uo5IXqU3spY30R84qm7jyATKqdaroQ4FyXOWMVatI7f2UDBYRWooVOApMqRtin49BilSVDltK3m5DCicv0yUUsD3cIRGGPWuoNDCuA5dlqhfJlEa6eRPnVAjBSi6lOAUUBIHaN5fjeYUdaSQbUfjo9j/87fnf99vv+20uprNJPTK6gVbBR5DL2sCJamu7ESjfBLFqRcEevURS1rjIFYHtQ/9yrysM2jbc51AqZt+gpJlwGUC7LRJmot0FcI2UfJvyf+AHf0wyc63Tcqs9NUdOGIDrqdwYGMDh0AdOaLyZIJkOoFCM8MT+KXKMG3rkkfsoCdepE9smS3YvsH6jTMsSQiLg4RQG1HGp4+mVJzynNpeb79+/XK/Xv6zS6kExV3zwhr2YVufznCWyDIFkz2dLFS3jJ1Y5sYmkS/D3LSnVQRKpYNw44F/r9veQOa2qc+kowQLlW6hYGTdc9/yGexuBsRXwZXFh1ZUWIRxjGaf0Mivsniu2KYFYCcvWwE0eF2m2ICQQbVAz9oyj9OXMGJpio1w2bNEmxiG2ErqSJsciVNwgsv+kbFDhN5SiVdgNs/PnGHXe5b62wOLmDuPlWwXEevvb/f35+fLb9e3jwwbVVcrYmsXxQrPXOexcX9Gc3FHsJCKVsarU17GKZb17iTd0CJsK8KWTCFBofQZS35BenVUk3EKIyeUlzFN0UOEVqA7aTAxcs4N5nOdoSGzGlDamPoQ4gFPvw8bB6ZgUojPZ6OrmddDP4EN8tRrjuqUHIkrX6oU22ZScoQwRW+krnbxqUBdumJo1RRr02vGyMg9hd7z0OdwnaO6+P7W0H+7qDx7+eeewgqWBcpCQkVY9huCUsdVPWJH/SWUY2CVrCTvVvf59QglV3hghaI/BWSGaQA3KyZYj9jx4wE33Biu0zZIdApKrqkfsdzhe8jMLmfcbTXBG5ZJqMBcHZlUua1MY4XHgeZj0HzEklgTs7Jx4OL8kcl6syiDKBIZnTOaEso2YY4W2SZYTqNwVyBYYtvmncAbojZ8xI4lvLsrH6FiWvtWBJttrDHeVPF/e79e9outjqRoghaThywdY1AY2v0AF8IF8JXaBzs4RkHW8XvCAT5+4AmoxchAu56w5go01+EHdAMDeTa2AtLLkQuqxD3zau1yCu+gP1eaOgZkHDkwAgjcOgaez2hPMz26NwodP7AromizuNNzbsMPcP5G5E2xVXCw6Te2+M4deZq7jh3vSuvcR2buNXT4KWNtNo/7GLO8JtrKawugEft5YQygJ75zivDOpNfW+TMEloodXUehv/wB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [City = _t, Year = _t, HousingAffordabilityIndex = _t, TransitScore = _t, GreenSpacePct = _t, EmissionsIndex = _t, LivabilityComposite = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"City", type text}, {"Year", Int64.Type}, {"HousingAffordabilityIndex", type number}, {"TransitScore", type number}, {"GreenSpacePct", type number}, {"EmissionsIndex", type number}, {"LivabilityComposite", type number}}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"City", "Year"}, "Attribute", "Value"),
				    #"Added Custom2" = Table.AddColumn(#"Unpivoted Columns", "ValueForGrouping", each if [Attribute]="HousingAffordabilityIndex"  or  [Attribute]="EmissionsIndex" then 100-[Value] else [Value]),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom2",{{"ValueForGrouping", type number}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type3",{{"Attribute", Order.Ascending},{"ValueForGrouping", Order.Descending}}),
				    #"Grouped Rows" = Table.Group(Table.Buffer(#"Sorted Rows"), {"Year", "Attribute"}, {{"Count", each _, type table [City=nullable text, Year=nullable number, Attribute=text, Value=number]}}),
				    #"Added Custom" = Table.AddColumn(#"Grouped Rows", "Custom", each Table.AddIndexColumn([Count],"Rank",1,1)),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"Year", "Attribute", "Count"}),
				    #"Expanded Custom" = Table.ExpandTableColumn(#"Removed Columns", "Custom", {"City", "Year", "Attribute", "Value", "ValueForGrouping", "Rank"}, {"City", "Year", "Attribute", "Value", "ValueForGrouping", "Rank"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Expanded Custom",{{"Rank", Int64.Type}, {"Attribute", type text}, {"Value", type number}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","EmissionsIndex","Emissions Index",Replacer.ReplaceText,{"Attribute"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","GreenSpacePct","Green Space Pct",Replacer.ReplaceText,{"Attribute"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","HousingAffordabilityIndex","Housing Affordability Index",Replacer.ReplaceText,{"Attribute"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","LivabilityComposite","Composite Livability",Replacer.ReplaceText,{"Attribute"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","TransitScore","Transit Score",Replacer.ReplaceText,{"Attribute"}),
				    #"Added Custom1" = Table.AddColumn(#"Replaced Value4", "AttributeOrder", each if [Attribute]="Composite Livability" then 1 else if [Attribute]="Housing Affordability Index" then 2 else if [Attribute]= "Emissions Index" then 3 else if [Attribute]= "Emissions Index" then 4 else 5),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"AttributeOrder", Int64.Type}, {"Year", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type2", {"City"}, #"City Lookup", {"City"}, "City Lookup", JoinKind.LeftOuter),
				    #"Expanded City Lookup" = Table.ExpandTableColumn(#"Merged Queries", "City Lookup", {"Region"}, {"Region"}),
				    #"Regional Grouping"= Table.Group(Table.Buffer(#"Expanded City Lookup"), {"Year", "Attribute", "Region"}, {{"Count", each _, type table [City=nullable text, Year=nullable number, Attribute=text, Value=number]}}),
				    #"RegionRank"= Table.AddColumn(#"Regional Grouping", "Custom", each Table.AddIndexColumn([Count],"Region Rank",1,1)),
				    #"Removed Columns1" = Table.RemoveColumns(RegionRank,{"Year", "Attribute", "Region", "Count"}),
				    #"Expanded Custom1" = Table.ExpandTableColumn(#"Removed Columns1", "Custom", {"City", "Year", "Attribute", "Value", "ValueForGrouping", "Rank", "AttributeOrder", "Region", "Region Rank"}, {"City", "Year", "Attribute", "Value", "ValueForGrouping", "Rank", "AttributeOrder", "Region", "Region Rank"}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Expanded Custom1",{{"City", type text}, {"Attribute", type text}, {"Region", type text}, {"Year", Int64.Type}, {"Rank", Int64.Type}, {"AttributeOrder", Int64.Type}, {"Region Rank", Int64.Type}, {"ValueForGrouping", type number}, {"Value", type number}})
				in
				    #"Changed Type4"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

