table 'Metric Renaming'
	lineageTag: f5580859-12e4-4a2c-94c8-572e486b836a

	column Attribute
		dataType: string
		lineageTag: c27f7223-407e-40d7-8a23-b1d4490addea
		summarizeBy: none
		sourceColumn: Attribute
		sortByColumn: AttributeOrder

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Attribute Slicer Name'
		dataType: string
		lineageTag: 12f901f4-f8d8-4614-9578-32eaa8f907e8
		summarizeBy: none
		sourceColumn: Attribute Slicer Name
		sortByColumn: AttributeOrder

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Attribute Header Name'
		dataType: string
		lineageTag: cd67bb95-7f8f-4320-ace1-8d4fa6b8121e
		summarizeBy: none
		sourceColumn: Attribute Header Name

		annotation SummarizationSetBy = Automatic

	column AttributeOrder
		dataType: int64
		formatString: 0
		lineageTag: 07bc8ecb-56c7-4530-b73d-fb760c51fd0e
		summarizeBy: sum
		sourceColumn: AttributeOrder

		annotation SummarizationSetBy = Automatic

	partition 'Metric Renaming' = m
		mode: import
		source =
				let
				    // This data was manually populated in Power Query.
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fVlNj+zGDfwrwZ4NQf3F7j4mQRDkYhjwwQfDh3l5k+wim51g3tr++yZZ1VrNqpWTrOctsckmi0XOzz8//eX+crn/73Z/f/ruKa6h2KMuoo8altr0mWRZ7b3Epdh7aUt9+uW7A9T+JvZF7BN1XXo3bNuwawQ29xm42qMtYs+aFqFhey0B/1z6kmSG9b9dl9WxeWluuC416DPXJWR9ymrvE3DHqaOfWpYcAHZvsp7ePi7BTn8Ex9UesgjD1fwkZUkB4Nxw7JZn4IBQZ3hs9lNfur2WupSCaLUZMuLMOSPS/p5Xi45i9J3RijOHY7JHgYOiUeqIND5S/ByK7VN/zWDMSAMpy2rvKduVKlbTJT74+/fb69fr259+fL5dXr99pFdSZzONB3hd7cSS6EG2D598QPABzw/RCAtdp+XoH9AbqGcfqDjy+EDLOHpIvOeKE/TTEzR8oPiRO+5NvyPAJ8C1CE7gHSkiDKFfh0Yg8Lr9+tNS5QTvKWfXNSJmx49LC0ibmhnAM/uedYmp6nlraPvvUaHZ/t8JOOLwnjPqewPcC0yDHxh8SWd4d1btFRj0U+eERN6CdwbO8Bw3FVGZljvwPDByEZ7/ePv1/fm/1/v1I+80TQqr2i9RKwi3LUvxMLYZUpAfyVMc1hRYmKjnuAqc84nWZCawMUHyObIB6cFSZMqgN3DvRi4zpJ8xo5SVNYHUu+b7eor0rMrM/iyoTz2tc7ilYz1Fki9hI8KGFmgmc7eKuLU6A5O43Fwu8DPT77Wc2mTNrIyt315soKHC2pojMwwGBGp1YCXpilXdBvzp5fX19vu/bvevuwyKoDiFNjaswrqHK3OoAJISsl3SLriyPiTfZ2ilNR5YIg7cCO3lHOpBKPSpoOAtSJHl83+sdviKaAkyzqolI77reZiQSPonHc/CJlcTqnQ9D1OkjwWJEztdZQ/t7RwZkQ+eg3rezIoJAeet58iEvA8jWzuQXqUieD+BsnH4bRZymBZbKoCmndUf7peX+8v1y/Vtl0zaQ7qbaQiw8urKJHNyUZaKc7T3QHVzCK2Gkuu8LRIiW+AB7Q2wwDBkVhxEnik+Tk5NddMflENBRtnFER37HE6h0Xns0QycKRLPol6LTOFofA2ZpSpv9GEXblYiCfATt0ffc0lWC1jGlAj7d0AZs+0f0BHGDKQ6z2WKHl2YPpXStqc52m1V2EiIHz6hOq8jaBSnByizSihPmThADcXXh9N/vV+/vf9+eb/ed5xFRlXnXLIoAflxE9POtGaaoikO0ggN3/0rWm1IfDFOmqErbEOQVXatxGsbZS0jWT6jG0/OSugVtjvRaL9i88kMzT7oJ5RM0klMlRUpZCefokcvdNt6XZ4xmU/L0/JwY5/RYUcLGrVMWe2d1Xox9fU6vbHREIWKyhtTpmBSXnIVYvPXNGojzxoLtLCbgzAypjlxXTBDZ9yr35z2luh+U1IOcrKTI2r/uN/evlx2iWalbQdokXPPmAs6xjfL/H6ECknFIG2onsReE6GfTCpOrFZY9VasVgvlK1KvLrz9Uo5IXqU3spY30R84qm7jyATKqdaroQ4FyXOWMVatI7f2UDBYRWooVOApMqRtin49BilSVDltK3m5DCicv0yUUsD3cIRGGPWuoNDCuA5dlqhfJlEa6eRPnVAjBSi6lOAUUBIHaN5fjeYUdaSQbUfjo9j/87fnf99vv+20uprNJPTK6gVbBR5DL2sCJamu7ESjfBLFqRcEevURS1rjIFYHtQ/9yrysM2jbc51AqZt+gpJlwGUC7LRJmot0FcI2UfJvyf+AHf0wyc63Tcqs9NUdOGIDrqdwYGMDh0AdOaLyZIJkOoFCM8MT+KXKMG3rkkfsoCdepE9smS3YvsH6jTMsSQiLg4RQG1HGp4+mVJzynNpeb79+/XK/Xv6zS6kExV3zwhr2YVufznCWyDIFkz2dLFS3jJ1Y5sYmkS/D3LSnVQRKpYNw44F/r9veQOa2qc+kowQLlW6hYGTdc9/yGexuBsRXwZXFh1ZUWIRxjGaf0Mivsniu2KYFYCcvWwE0eF2m2ICQQbVAz9oyj9OXMGJpio1w2bNEmxiG2ErqSJsciVNwgsv+kbFDhN5SiVdgNs/PnGHXe5b62wOLmDuPlWwXEevvb/f35+fLb9e3jwwbVVcrYmsXxQrPXOexcX9Gc3FHsJCKVsarU17GKZb17iTd0CJsK8KWTCFBofQZS35BenVUk3EKIyeUlzFN0UOEVqA7aTAxcs4N5nOdoSGzGlDamPoQ4gFPvw8bB6ZgUojPZ6OrmddDP4EN8tRrjuqUHIkrX6oU22ZScoQwRW+krnbxqUBdumJo1RRr02vGyMg9hd7z0OdwnaO6+P7W0H+7qDx7+eeewgqWBcpCQkVY9huCUsdVPWJH/SWUY2CVrCTvVvf59QglV3hghaI/BWSGaQA3KyZYj9jx4wE33Biu0zZIdApKrqkfsdzhe8jMLmfcbTXBG5ZJqMBcHZlUua1MY4XHgeZj0HzEklgTs7Jx4OL8kcl6syiDKBIZnTOaEso2YY4W2SZYTqNwVyBYYtvmncAbojZ8xI4lvLsrH6FiWvtWBJttrDHeVPF/e79e9outjqRoghaThywdY1AY2v0AF8IF8JXaBzs4RkHW8XvCAT5+4AmoxchAu56w5go01+EHdAMDeTa2AtLLkQuqxD3zau1yCu+gP1eaOgZkHDkwAgjcOgaez2hPMz26NwodP7AromizuNNzbsMPcP5G5E2xVXCw6Te2+M4deZq7jh3vSuvcR2buNXT4KWNtNo/7GLO8JtrKawugEft5YQygJ75zivDOpNfW+TMEloodXUehv/wB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [City = _t, Year = _t, HousingAffordabilityIndex = _t, TransitScore = _t, GreenSpacePct = _t, EmissionsIndex = _t, LivabilityComposite = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"City", type text}, {"Year", Int64.Type}, {"HousingAffordabilityIndex", type number}, {"TransitScore", type number}, {"GreenSpacePct", type number}, {"EmissionsIndex", type number}, {"LivabilityComposite", type number}}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"City", "Year"}, "Attribute", "Value"),
				    #"Removed Other Columns" = Table.SelectColumns(#"Unpivoted Columns",{"Attribute"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Replaced Value" = Table.ReplaceValue( #"Removed Duplicates","EmissionsIndex","Emissions Index",Replacer.ReplaceText,{"Attribute"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","GreenSpacePct","Green Space Pct",Replacer.ReplaceText,{"Attribute"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","HousingAffordabilityIndex","Housing Affordability Index",Replacer.ReplaceText,{"Attribute"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","LivabilityComposite","Composite Livability",Replacer.ReplaceText,{"Attribute"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","TransitScore","Transit Score",Replacer.ReplaceText,{"Attribute"}),
				    #"Added Custom" = Table.AddColumn(#"Replaced Value4", "Attribute Slicer Name", each if [Attribute]="Housing Affordability Index" then "Housing" else if [Attribute]="Transit Score" then "Transit" else if [Attribute]="Green Space Pct" then "Green Space" else if [Attribute]="Emissions Index" then "Emissions" else "Livability"),
				    #"Added Custom2" = Table.AddColumn( #"Added Custom", "Attribute Header Name", each if [Attribute]="Housing Affordability Index" then "Housing Affordability" else if [Attribute]="Transit Score" then "Transit Quality" else if [Attribute]="Green Space Pct" then "City Green Space" else if [Attribute]="Emissions Index" then "Emissions" else "Composite Livability"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom2",{{"Attribute Slicer Name", type text}, {"Attribute Header Name", type text}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "AttributeOrder", each if [Attribute]="Composite Livability" then 1 else if [Attribute]="Housing Affordability Index" then 2 else if [Attribute]= "Emissions Index" then 3 else if [Attribute]= "Green Space Pct" then 4 else 5),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"AttributeOrder", Int64.Type}})
				
				in
				    #"Changed Type2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

